name: Auto-Setup Packagist Webhook

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/auto-webhook.yml'

jobs:
  setup-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Packagist Webhook
      run: |
        echo "🔗 Setting up Packagist webhook automatically..."
        
        # Create webhook using GitHub API
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "packagist-webhook",
            "active": true,
            "events": ["push"],
            "config": {
              "url": "https://packagist.org/api/update-package",
              "content_type": "application/json",
              "secret": "",
              "insecure_ssl": "0"
            }
          }' \
          "https://api.github.com/repos/${{ github.repository }}/hooks"
          
        echo "✅ Packagist webhook setup attempted!"
        echo "🔗 Check webhooks at: https://github.com/${{ github.repository }}/settings/hooks"
        
    - name: Test Packagist Integration
      run: |
        echo "🧪 Testing Packagist integration..."
        
        # Test if Packagist can access the repository
        curl -s "https://packagist.org/api/update-package" \
          -H "Content-Type: application/json" \
          -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}'
          
        echo "✅ Packagist integration test completed!"
        
    - name: Notify Success
      run: |
        echo "🎉 Packagist webhook setup completed!"
        echo "📊 Repository: ${{ github.repository }}"
        echo "🔗 Webhook: https://packagist.org/api/update-package"
        echo "🚀 Next: Submit to Packagist at https://packagist.org/packages/submit"
